# heroku_san configuration, for easy multi-env deployments to heroku.
# Otherwise you've got to append --app appname all the fucking time.
#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: high-lightning-781
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  app: quiet-fog-435
  config: &default
    BUNDLE_WITHOUT: "development:test"
